### PR TITLE
Add header component

### PR DESCRIPTION
**Pull request by tombiddulph**
This is great library, I've been learning Blazor recently and I decided to try and add one of the easier components to implement. It's still a work in progress at the moment. I've tried to copy and implement the examples from this page https://semantic-ui.com/elements/header.html

I'm not overly happy about the `NumberedHeader` enum to support `<h1>` etc tags, have you got any thoughts on how I could improve it?

@strakamichal  any thoughts?

### CODE REVIEW

**Comment by tombiddulph** [comment]
I've refactored a bit and added most of the examples from the semantic ui docs. What do you think @strakamichal

**Comment by strakamichal** [comment]
Hi @tombiddulph,
Do you think it is necessary to move from .net 5 to .net8? I'm thinking about compatibility with older projects...

**Comment by JelleHissink** [comment]
If you are still using .net 5 you are more then 2 years or so out of support. 
For me if a library is still targeting .net 5. It is a first indication of lack of maintainance. 
Also you are locking yourself out of newer features by doing this. The question is are you still actively testing against the current version if you rely on everything that was part of .net 5?
My 2-cents, just follow the .Net release cycle as a baseline of what to support.

**Comment by tombiddulph** [comment]
Yep as @JelleHissink mentioned, .NET 5 is a few years out of support. Perhaps you could bump the major version of the library to move to .NET 8? [The support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) can be found here. .NET 8 will be supported for the best part of 2 years from now 👍

**Comment by strakamichal** [comment]
So, what about to move to .NET 6 for now and after November 12, 2024 move to .NET 8? We are using this library at the company and we did't move all projects to .NET 8 yet.

**Comment by tombiddulph** [comment]
Sure I can do that if you want, I've only changed the `SemanticBlazor.Web` project, `SemanticBlazor` is still targeting `netstandard2.1` so it shouldn't cause any issues,

**Comment by strakamichal** [comment]
> Sure I can do that if you want, I've only changed the `SemanticBlazor.Web` project, `SemanticBlazor` is still targeting `netstandard2.1` so it shouldn't cause any issues,

Oh lord, my fault. Then it's all correct.

**Pull request merged**
